version: '3.9'

services:
  server:
    container_name: go-server
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      - TZ=Asia/Tokyo
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - PORT=${SERVICE_PORT}
    depends_on: 
      - db

  db: 
    image: postgres:16
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 3


