pkgname = "model"
output   = "pkg/domain/model"
wipe     = true
no-tests = true
add-global-variants = true
add-soft-deletes = true

[psql]
  dbname = "app"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  schema = "app"
  sslmode = "disable"
